version: "3.2"
services:
  database:
    container_name: database
    image: postgres:latest
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=develop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: bash -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate --noinput &&
        python3 manage.py runserver 0.0.0.0:8000
      "

    depends_on:
      - database

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    # tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

volumes:
  postgres-data:
