# Generated by Django 3.0.4 on 2020-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('title_english', models.CharField(max_length=100)),
                ('content_english', models.TextField()),
                ('code', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/contents/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='Cverdiane', max_length=100)),
                ('role_english', models.CharField(default='Cverdian', max_length=100)),
                ('avatar', models.ImageField(upload_to='images/team_members/')),
                ('position', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
