# Generated by Django 3.0.4 on 2020-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalcontents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
