# Generated by Django 3.0.4 on 2020-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalcontents', '0002_auto_20200427_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/contents/'),
        ),
    ]
